improve the dizzywrapper to download/locally install more packages

diff --git a/d1zzy b/d1zzy
--- a/d1zzy
+++ b/d1zzy
@@ -1,40 +1,66 @@
 #!/bin/zsh
 dizzydir=${0:h:A}
-deps=( \
-	$dizzydir/deps/OpenGL-Simple-0.04/blib/arch/ \
-	$dizzydir/deps/OpenGL-Simple-0.04/blib/lib/ \
-	$dizzydir/deps/OpenGL-Simple-GLUT-0.03/blib/arch/ \
-	$dizzydir/deps/OpenGL-Simple-GLUT-0.03/blib/lib/ \
-)
-deps_cmd=-I${(j: -I:)deps}
-deps_lib=${(j/:/)deps}
 
-echo "*** checking if dependencies are present"
-if ! perl ${=deps_cmd} -MOpenGL::Simple -MOpenGL::Simple::GLUT -e ''
-then
-	trap 'echo "*** failed to build dependencies - cannot resume"; exit 1' ERR
-	echo "*** building dependencies now. stand by"
-	rm -rf $dizzydir/deps
-	mkdir -p $dizzydir/deps
-	pushd $dizzydir/deps
+function install_mod() {
+	trap 'echo -e "\e[1;31m*** failed to build dependencies - cannot resume\e[m"; exit 1' ERR
+	echo -e "\e[1;32m*** building $1\e[m"
 
-	wget http://search.cpan.org/CPAN/authors/id/J/JC/JCHIN/OpenGL-Simple-0.03.tar.gz
-	wget http://search.cpan.org/CPAN/authors/id/J/JC/JCHIN/OpenGL-Simple-GLUT-0.03.tar.gz
-	tar xf OpenGL-Simple-0.03.tar.gz
-	tar xf OpenGL-Simple-GLUT-0.03.tar.gz
-	cp -a OpenGL-Simple-0.03 OpenGL-Simple-0.04
-	cd OpenGL-Simple-0.04
-	patch -Np1 -i $dizzydir/OpenGL-Simple-texturebinding.diff
-	perl Makefile.PL
+	rm -rf $dizzydir/deps_build
+	mkdir -p $dizzydir/deps_build
+	pushd $dizzydir/deps_build
+
+	modname=$1
+	precommands=${2:-true}
+
+	tarball=$(   \
+		wget -q -O - 'http://search.cpan.org/search?mode=dist&query='$modname \
+		| egrep ${modname//::/-}'-[0-9]' \
+		| cut -d\" -f 2 \
+		| head -n 1 \
+		| sed 's/^/http:\/\/search.cpan.org/' \
+		| xargs wget -q -O - \
+		| fgrep .tar \
+		| cut -d\" -f 2 \
+		| sed 's/^/http:\/\/search.cpan.org/' \
+	)
+	wget $tarball
+	tar xf ${tarball:t}
+	cd ${modname//::/-}-*/
+	if [[ -n $precommands ]]
+	then
+		${=precommands}
+	fi
+	perl Makefile.PL PREFIX=$dizzydir/deps_install
 	make
-	cd ..
-	cd OpenGL-Simple-GLUT-0.03
-	perl Makefile.PL
-	make
+	make install
 	cd ..
 
 	popd
+
+	echo -e "\e[1;32m*** successfully built $1\e[m"
+
 	trap - ERR
-fi
-export PERL5LIB=${PERL5LIB}:$deps_lib
+}
+
+function check_mod() {
+	wank=$1
+	shift
+	if perl -I$dizzydir/deps_install/share/perl/ -I$dizzydir/deps_install/lib/perl -M$wank $* -e ''
+	then
+		echo -e "\e[1;32m*** $wank present\e[m"
+		return 0
+	else
+		echo -e "\e[1;31m*** $wank NOT present\e[m"
+		return 1
+	fi
+}
+
+check_mod OpenGL::Simple \
+|| install_mod OpenGL::Simple "patch -Np1 -i $dizzydir/OpenGL-Simple-texturebinding.diff"
+check_mod OpenGL::Simple::GLUT \
+|| install_mod OpenGL::Simple::GLUT
+check_mod Convert::Color \
+|| install_mod Convert::Color
+
+export PERL5LIB=${PERL5LIB}:$dizzydir/deps_install/lib/perl:$dizzydir/deps_install/share/perl/
 exec $dizzydir/dizzy $*
